"""
Report generation: produces a PDF investigative summary and CSV exports
of the underlying data, for hand-off to a human analyst or inclusion in
a case file.
"""
import csv
import io
from datetime import datetime

from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

NAVY = colors.HexColor("#0D1117")
MUTED = colors.HexColor("#57606A")
BORDER = colors.HexColor("#D0D7DE")
DANGER = colors.HexColor("#CF222E")


def build_case_pdf(engine, case_id, centrality, communities, anomalies, link_predictions) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=letter, topMargin=0.6*inch, bottomMargin=0.6*inch,
                             leftMargin=0.6*inch, rightMargin=0.6*inch)
    styles = getSampleStyleSheet()
    title = ParagraphStyle("T", parent=styles["Title"], fontName="Helvetica-Bold",
                            fontSize=18, textColor=NAVY, spaceAfter=2)
    sub = ParagraphStyle("S", parent=styles["Normal"], fontSize=10, textColor=MUTED, spaceAfter=10)
    h2 = ParagraphStyle("H2", parent=styles["Heading2"], fontName="Helvetica-Bold",
                         fontSize=13, textColor=NAVY, spaceBefore=14, spaceAfter=6)
    body = ParagraphStyle("B", parent=styles["Normal"], fontSize=9.5, leading=13.5, spaceAfter=3)
    disclaimer = ParagraphStyle("D", parent=styles["Normal"], fontSize=8.5,
                                 textColor=MUTED, fontName="Helvetica-Oblique", leading=12)

    story = [
        Paragraph(f"Case Report — {case_id}", title),
        Paragraph(f"Generated {datetime.now().strftime('%Y-%m-%d %H:%M')} · "
                  f"{len(engine.entities)} entities · {len(engine.artifacts)} artifacts", sub),
        HRFlowable(width="100%", thickness=1, color=BORDER, spaceAfter=8),
        Paragraph(
            "This report is an investigative aid generated by automated network analysis. "
            "Scores and rankings below are triage signals for analyst review — they are not "
            "determinations of guilt, involvement, or any legal conclusion.",
            disclaimer
        ),
    ]

    story.append(Paragraph("Top Entities by Centrality (likely intermediaries)", h2))
    rows = [["Entity", "Betweenness", "Degree", "Eigenvector"]]
    for r in centrality[:8]:
        rows.append([r["name"], str(r["betweenness_centrality"]), str(r["degree_centrality"]), str(r["eigenvector_centrality"])])
    story.append(_table(rows))

    story.append(Paragraph("Detected Communities", h2))
    for c in communities:
        names = ", ".join(m["name"] for m in c["members"])
        story.append(Paragraph(f"<b>Cluster {c['community_id']+1}</b> ({c['size']} entities): {names}", body))

    story.append(Paragraph("Highest Anomaly-Score Entities", h2))
    rows = [["Entity", "Anomaly Score", "Degree", "Off-Hour Ratio"]]
    for r in anomalies[:8]:
        rows.append([r["name"], str(r["anomaly_score"]), str(r["degree"]), str(r["off_hour_activity_ratio"])])
    story.append(_table(rows))

    story.append(Paragraph("Predicted (Unconfirmed) Links", h2))
    rows = [["Entity A", "Entity B", "Predicted Score"]]
    for p in link_predictions[:8]:
        rows.append([p["entity_a_name"], p["entity_b_name"], str(p["predicted_score"])])
    story.append(_table(rows))

    doc.build(story)
    return buf.getvalue()


def _table(rows):
    t = Table(rows, colWidths=None)
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), NAVY),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8.5),
        ("GRID", (0, 0), (-1, -1), 0.4, BORDER),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F6F8FA")]),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    return t


def build_entities_csv(engine) -> str:
    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow(["entity_id", "name", "phone", "device_id", "ip"])
    for eid, e in engine.entities.items():
        writer.writerow([eid, e.get("name"), e.get("phone"), e.get("device_id"), e.get("ip")])
    return buf.getvalue()


def build_artifacts_csv(engine) -> str:
    buf = io.StringIO()
    fieldnames = ["record_type", "record_id", "timestamp", "caller_id", "callee_id",
                  "sender_id", "receiver_id", "owner_id", "transferred_to_id",
                  "entity_id", "duration_sec", "platform", "filename", "url", "lat", "lng"]
    writer = csv.DictWriter(buf, fieldnames=fieldnames, extrasaction="ignore")
    writer.writeheader()
    for art in engine.artifacts:
        writer.writerow(art)
    return buf.getvalue()


def build_analysis_csv(centrality, anomalies) -> str:
    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow(["entity_id", "name", "degree_centrality", "betweenness_centrality",
                      "eigenvector_centrality", "anomaly_score"])
    anomaly_map = {a["entity_id"]: a["anomaly_score"] for a in anomalies}
    for r in centrality:
        writer.writerow([r["entity_id"], r["name"], r["degree_centrality"],
                          r["betweenness_centrality"], r["eigenvector_centrality"],
                          anomaly_map.get(r["entity_id"], "")])
    return buf.getvalue()
